<a href="https://colab.research.google.com/github/akash5169/Deep-Learning/blob/main/Neural_Network_To_Add_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
import numpy as np

In [91]:
# Step 1 : Initialize the weights
# Step 2 : Forward propogate and find activations and the output
# Step 3 : find the error at the end
# Step 4 : backpropogate and find the updated weights by minizing the error with gradient descent 
# Step 5 : reapeat step 2 to 4 until convergence


class MLP:
  def _sigmoid(self, h):
    return 1/(1+np.exp(-h))

  def __init__(self, num_inputs=3, hidden_layers=[3,3], num_ouputs=2):
    self.num_inputs=num_inputs
    self.hidden_layers=hidden_layers
    self.num_ouputs=num_ouputs

    layers = [num_inputs]+ hidden_layers+[num_ouputs]

    weights=[]

    for i in range (len(layers)-1):
      w=np.random.rand(layers[i],layers[i+1])
      weights.append(w)
    
    self.weights=weights

    derivatives=[]
    for i in range (len(layers)-1):
      d=np.zeros((layers[i],layers[i+1]))
      derivatives.append(d)

    self.derivatives=derivatives

    activations=[]
    for i in range (len(layers)):
      a=np.zeros(layers[i])
      activations.append(a)
    self.activations=activations

  def forward_propogate(self,inputs):
    activations=inputs
    self.activations[0]=activations
    
    for i,w in enumerate(self.weights):
      net_inputs=np.dot(activations, w)
      activations=self._sigmoid(net_inputs)
      self.activations[i+1]=activations

    return activations

  def back_propogate(self,error, verbose=False):
    for i in reversed(range(len(self.derivatives))):
      activations=self.activations[i+1]

      delta= error * self._sigmoid_derivative(activations)

      delta_reshaped= delta.reshape(delta.shape[0], -1).T

      current_activations= self.activations[i] # ndarray ([0.1,0.2]) --> ndarray([[0.1],[0.2]])

      current_activations= current_activations.reshape(current_activations.shape[0], -1)

      self.derivatives[i]=np.dot(current_activations, delta_reshaped)

      error=np.dot(delta, self.weights[i].T)

      if verbose:
        print("Derivatives for W{}: {}".format(i,self.derivatives[i]))
    return error

 

  def train(self, inputs, targets, epochs, learning_rate):
    for i in range(epochs):

      sum_error=0
      for input,target in zip(inputs,targets):
        #perform forward prop
        output=self.forward_propogate(input)

        #calculate erro
        error=target-output

        #backpropogate
        self.back_propogate(error)

        #apply gradiet descent
        self.gradient_descent(learning_rate)

        #report the error
        sum_error=sum_error + self._mse(target,output)

      print("Error:{} at epoch {}".format(sum_error/ len(inputs), i+1))
    
  def gradient_descent(self, learning_rate):
    for i  in range(len(self.weights)):
      weights= self.weights[i]

      #print("Original Weights {} {}".format(i,weights))
      derivatives=self.derivatives[i]
      weights +=derivatives * learning_rate
      
      #print("updated Weights {} {}".format(i,weights))

  def _sigmoid_derivative(self,x):
    return x * (1.0-x)

  def _mse(self, target, output):
    return np.average((target-output)**2 )

  

In [92]:
from random import random
if __name__=="__main__":
  mlp= MLP(2, [5], 1) 
 
  #create a dataset
  inputs=np.array([[ random() / 2 for _ in range(2)] for _ in range(1000)])
  targets=np.array([[i[0] + i[1]] for i in inputs])

  #train our mlp
  mlp.train(inputs, targets, 50, 1)

  input=np.array([.25,.15])
  #target=np.array([.3])

  output=mlp.forward_propogate(input)

  print()
  print()

  print(output)



Error:0.0432529361691046 at epoch 1
Error:0.024569381994323562 at epoch 2
Error:0.006304663566896839 at epoch 3
Error:0.00189951371491211 at epoch 4
Error:0.0009686899730897157 at epoch 5
Error:0.0007338871180933378 at epoch 6
Error:0.0006587164683213484 at epoch 7
Error:0.0006240274324235437 at epoch 8
Error:0.0006010612691766652 at epoch 9
Error:0.0005825634000900576 at epoch 10
Error:0.0005665836980274415 at epoch 11
Error:0.0005524814998961838 at epoch 12
Error:0.0005399412257007663 at epoch 13
Error:0.0005287390274913205 at epoch 14
Error:0.0005186906471508239 at epoch 15
Error:0.0005096395156403166 at epoch 16
Error:0.0005014524637699036 at epoch 17
Error:0.0004940165171784907 at epoch 18
Error:0.00048723589732161413 at epoch 19
Error:0.0004810292912235387 at epoch 20
Error:0.0004753274787697142 at epoch 21
Error:0.0004700713311599394 at epoch 22
Error:0.00046521014866631133 at epoch 23
Error:0.0004607002896989297 at epoch 24
Error:0.00045650404230719555 at epoch 25
Error:0.00045

In [87]:
b=np.array([[0.16308476 ,0.57923519 ,0.10509013 ,0.84817566, 0.89973497]
 ,[0.88206471, 0.33850809, 0.27557758, 0.66225708, 0.44814947]])
a=np.array([[ 0.00017159,  0.00155403, -0.00070605, -0.00011337,  0.00014874],
 [ 0.00019405,  0.00175741, -0.00079846, -0.00012821,  0.00016821]])
b=b+a*0.1
print(b)

[[0.16310192 0.57939059 0.10501953 0.84816432 0.89974984]
 [0.88208411 0.33868383 0.27549773 0.66224426 0.44816629]]


In [86]:
b=np.array([[0.16308476 ,0.57923519 ,0.10509013 ,0.84817566, 0.89973497]
 ,[0.88206471, 0.33850809, 0.27557758, 0.66225708, 0.44814947]])
a=np.array([[ 0.00017159,  0.00155403, -0.00070605, -0.00011337,  0.00014874],
 [ 0.00019405,  0.00175741, -0.00079846, -0.00012821,  0.00016821]])
b+=a*0.1
print(b)

[[0.16310192 0.57939059 0.10501953 0.84816432 0.89974984]
 [0.88208411 0.33868383 0.27549773 0.66224426 0.44816629]]
